### ISSUE TITLE
FatalThrowableError in FrontController.php line 12:

### ISSUE THREAD

**Issue by DeeJaVu** [yangjianyi/coding_farmer#1]
why do i get this error

Call to undefined function App\Http\Controllers\Front\getIP()

Line12
`dispatch(new CountViewer('', '', $_SERVER['REQUEST_URI'], $_SERVER['REQUEST_METHOD'], $_SERVER['HTTP_USER_AGENT'], getIP()));`

**Comment by yangjianyi** [comment]
@DeeJaVu  oh..sorry, I forget upload getIp() this function... i will update this function later.. thanks.

**Comment by yangjianyi** [comment]
@DeeJaVu 
I have defined it in the file
`/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php`
the last line..

![image](https://cloud.githubusercontent.com/assets/9440426/23172278/3dd4a946-f890-11e6-90c3-baf9fe8eafd9.png)

may be u `overwrite` this file when u execute `composer update`
